name = "tafsirfrench"
compatibility_date = "2024-12-01"
main = "./site/worker.js"

[assets]
directory = "./site/dist"

[[kv_namespaces]]
binding = "TAFSIR_AUTH"
id = "2358aae9ee1a488199050694db689654"

[ai]
binding = "AI"
